-- DATETIME에서 시간만 빼려면 HOUR(datetime)라는 함수를 쓰자
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME)
FROM ANIMAL_OUTS
-- WHERE DATETIME BETWEEN '09:00' AND '19:59'
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);