-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY = P.CATEGORY
)
HAVING CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
ORDER BY PRICE DESC;